import { Link } from 'react-router-dom'
import { MarketingNav } from './MarketingHome'

export function AboutPage() {
  return <div className="marketing-site about-site"><MarketingNav /><main>
    <section className="about-hero"><div className="marketing-container"><span className="marketing-kicker"><i /> ABOUT TRUVOID</span><h1>Identity infrastructure for a more trusted digital economy.</h1><p>We remove the friction between a good decision and the evidence behind it, giving organizations a clearer way to verify people, businesses, and the operations that connect them.</p><div className="about-proof"><span><b>01</b> Organizations</span><span><b>02</b> Customers</span><span><b>03</b> Developers</span></div></div></section>
    <section className="marketing-section muted"><div className="marketing-container"><div className="stakeholder-grid">{[['01 / STAKEHOLDER', 'Organizations', 'Organizations need to know who they are dealing with across complex frameworks and real operating conditions.'], ['02 / END USERS', 'Customers', 'Customers need confidence that identity information is handled responsibly and with restraint.'], ['03 / ARCHITECTS', 'Developers', 'Developers need reliable infrastructure with clear contracts, scoped access, and predictable operations.']].map(([label, title, copy]) => <article key={label}><span className="marketing-kicker"><i /> {label}</span><h3>{title}</h3><p>{copy}</p><b>→</b></article>)}</div><div className="about-synthesis"><span className="marketing-kicker">PLATFORM SYNTHESIS</span><h2>One identity layer for all three.</h2><span className="live-status"><i /> Workspace and verification operations connected</span></div></div></section>
    <section className="marketing-section"><div className="marketing-container"><div className="about-heading"><span className="marketing-kicker"><i /> CORE CAPABILITY</span><h2>What we do.</h2><p>TruvoID brings verification, API access, wallet operations, and visibility into one workspace.</p></div><div className="capability-grid">{[['01', 'Verification', 'Verify people and businesses against the records and services your workflow requires.', 'KYC / KYB'], ['02', 'API access', 'Connect your product with scoped credentials, consistent requests, and clear activity.', 'REST / WEBHOOKS'], ['03', 'Wallet operations', 'Fund verification work and keep organization or outlet usage visible.', 'CONTROLLED USAGE'], ['04', 'Operational visibility', 'Give teams a shared view of setup, access, activity, and the decisions in flight.', 'ONE WORKSPACE']].map(([number, title, copy, tag]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p><b>{tag}</b></article>)}</div></div></section>
    <section className="marketing-section muted about-approach"><div className="marketing-container"><div className="approach-layout"><div><span className="marketing-kicker"><i /> OPERATING PHILOSOPHY</span><h2>Simple for teams. Deterministic for systems.</h2><p>We are building an identity verification layer that replaces fragmented portals, fragile handoffs, and disconnected compliance records with a focused operational workspace.</p><Link className="marketing-button primary" to="/solutions">See how it works <span>↗</span></Link></div><div className="principle-list">{[['01', 'Data minimization', 'Use the information required for the decision, not everything available.'], ['02', 'One operational console', 'Give compliance, operations, and engineering a shared source of truth.'], ['03', 'Developer-grade reliability', 'Make access predictable, scoped, observable, and easy to change.']].map(([number, title, copy]) => <div key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></div></section>
    <section className="marketing-section contact-section"><div className="marketing-container contact-layout"><div><span className="marketing-kicker"><i /> COMMUNICATIONS</span><h2>Let’s build more trusted experiences.</h2><p>Whether you are verifying customers, onboarding businesses, or integrating identity into your product, we would like to hear from you.</p><div className="contact-details"><span><b>EMAIL</b><a href="mailto:contact@truvoid.com">contact@truvoid.com</a></span><span><b>OPERATIONS</b><strong>Lagos, Nigeria</strong></span><span><b>SUPPORT</b><strong>Mon – Fri / 08:00 – 18:00 WAT</strong></span></div></div><form className="contact-card" onSubmit={event => event.preventDefault()}><span className="marketing-kicker">TALK TO TRUVOID</span><input aria-label="Full name" placeholder="Full name" required /><input aria-label="Work email" placeholder="Work email" required type="email" /><input aria-label="Organization" placeholder="Organization" required /><select aria-label="Primary interest" defaultValue=""><option disabled value="">Primary interest</option><option>Institution verification</option><option>Agency and outlets</option><option>API integration</option><option>Enterprise conversation</option></select><textarea aria-label="Message" placeholder="Tell us what you are building." required rows={4} /><button className="marketing-button primary" type="submit">Send message <span>↗</span></button><small>We will use your details only to respond to this conversation.</small></form></div></section>
    <section className="marketing-cta"><div className="marketing-container"><span className="marketing-kicker">THE TRUST LAYER</span><h2>Know who you’re dealing with.</h2><p>Start with a workspace and build the right identity operations around it.</p><Link className="marketing-button gold" to="/register">Create a workspace <span>↗</span></Link></div></section>
  </main><footer className="marketing-footer"><div className="marketing-container footer-bottom"><span>© 2026 TruvoID</span><span>Verify. Know. Operate.</span></div></footer></div>
}
