import { useState } from 'react'
import { Link } from 'react-router-dom'
import { MarketingNav } from './MarketingHome'

const steps = [['01', 'Register an outlet', 'Provision an isolated outlet identity inside your organization.'], ['02', 'Issue credentials', 'Generate a scoped key for the service or outlet that will use it.'], ['03', 'Call the API', 'Send a JSON request with consent and an idempotency key.'], ['04', 'Receive the result', 'Get a deterministic match response with a usable reference.'], ['05', 'Monitor operations', 'Review usage, activity, wallets, and credential state.']]

export function ApiDevelopersPage() {
  const [response, setResponse] = useState(false)
  const snippet = `curl -X POST https://api.gettruvoid.com/v1/verify/nin -H "X-API-Key: trv_test_••••" -H "Content-Type: application/json" -d '{ "number": "00000000001" }'`
  return <div className="marketing-site developer-site"><MarketingNav /><main>
    <section className="developer-hero"><div className="marketing-container developer-hero-grid"><div><span className="marketing-kicker"><i /> DEVELOPER INFRASTRUCTURE</span><h1>Identity verification, connected to your product.</h1><p>Build verification into customer onboarding, business checks, and risk workflows with scoped credentials and a clear operational trail.</p><div className="hero-actions"><a className="marketing-button primary" href="#console">Read the request <span>↓</span></a><Link className="marketing-button ghost" to="/register">Get API access <span>↗</span></Link></div><div className="developer-specs"><span><b>REST</b> JSON endpoints</span><span><b>WEBHOOKS</b> Event-ready</span><span><b>SCOPED</b> Outlet credentials</span></div></div><div className="developer-console" id="console"><div className="dev-console-head"><span><i /> <i /> <i /> REST / VERIFICATION</span><b>TLS / ENCRYPTED</b></div><div className="dev-tabs"><button className={!response ? 'active' : ''} onClick={() => setResponse(false)}>Request</button><button className={response ? 'active' : ''} onClick={() => setResponse(true)}>Response / 200</button></div><pre>{response ? <code><span>{'{'}</span>{'\n  '}<em>"status"</em>: <strong>"match"</strong>,{'\n  '}<em>"reference"</em>: <strong>"TRV_REF_83901928"</strong>,{'\n  '}<em>"verified"</em>: <b>true</b>,{'\n  '}<em>"confidence"</em>: <b>0.998</b>{'\n'}<span>{'}'}</span></code> : <code><span className="comment">{snippet}</span></code>}</pre><div className="dev-console-foot"><span>{response ? '200 OK / response ready' : 'POST /v1/verify/nin'}</span><button onClick={() => void navigator.clipboard?.writeText(snippet)}>Copy snippet</button></div></div></div></section>
    <section className="marketing-section how-it-works"><div className="marketing-container"><div className="section-heading-marketing"><span className="marketing-kicker"><i /> INTEGRATION ARCHITECTURE</span><h2>From first request to trusted result.</h2><p>A small, legible integration surface for engineering teams and the operators who support them.</p></div><div className="integration-steps">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p><b>STEP {number}</b></article>)}</div></div></section>
    <section className="marketing-section muted"><div className="marketing-container"><div className="section-heading-marketing"><span className="marketing-kicker"><i /> RUNTIME MODEL</span><h2>Built for real operations.</h2><p>Keep experimentation separate from the workflows that serve real customers.</p></div><div className="environment-grid">{[['SANDBOX', 'Test safely', 'Explore request shapes with synthetic data before your team connects production systems.'], ['STAGING', 'Validate together', 'Run integration checks with your engineers, compliance owners, and outlet administrators.'], ['PRODUCTION', 'Operate with control', 'Use scoped live credentials and monitor verification activity from your workspace.']].map(([label, title, copy], index) => <article className={index === 2 ? 'environment-card live' : 'environment-card'} key={label}><span>{label}</span><h3>{title}</h3><p>{copy}</p><div>API / {index === 0 ? 'test' : index === 1 ? 'pre-production' : 'live'}</div></article>)}</div></div></section>
    <section className="marketing-section control-section"><div className="marketing-container control-grid"><div><span className="marketing-kicker"><i /> GOVERNANCE & CONTROL</span><h2>Your keys. Your integrations. Your control.</h2><p>Credentials should be easy to create, scoped to the right operating unit, and simple to revoke when a system changes.</p><a className="text-link" href="/api-docs.html">Open API documentation →</a></div><div className="control-list">{['Scoped outlet credentials', 'Single-reveal secrets', 'Fast credential revocation', 'Idempotent requests', 'Usage and wallet visibility', 'Audit-ready activity'].map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><i>✓</i></div>)}</div></div></section>
    <section className="marketing-section muted"><div className="marketing-container"><div className="section-heading-marketing"><span className="marketing-kicker"><i /> BUILD FOR THE MOMENT</span><h2>Where teams use TruvoID.</h2></div><div className="use-case-grid">{[['Customer onboarding', 'Confirm a customer before an account, wallet, or service is activated.'], ['Business onboarding', 'Validate a company and its people before creating commercial access.'], ['Fraud prevention', 'Add an identity signal before high-risk actions and payouts.'], ['Tax compliance', 'Corroborate business identifiers inside controlled workflows.'], ['Ongoing monitoring', 'Keep verification activity visible as operations scale.']].map(([title, copy]) => <article key={title}><span>↗</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="marketing-cta"><div className="marketing-container"><span className="marketing-kicker">READY WHEN YOUR TEAM IS</span><h2>Build verification into the moments that matter.</h2><p>Start with the documentation, create a workspace, and connect your first outlet when the operation is ready.</p><div className="hero-actions"><Link className="marketing-button gold" to="/register">Create a workspace <span>↗</span></Link><a className="marketing-button dark-ghost" href="mailto:hello@truvoid.com">Talk to engineering</a></div></div></section>
  </main><footer className="marketing-footer"><div className="marketing-container footer-bottom"><span>© 2026 TruvoID</span><span>Developer infrastructure for identity operations.</span></div></footer></div>
}
