import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { api, AuthProfile, tokenStore } from './api'
import { ApiKeysPage } from './ApiKeysPage'
import { OrganizationSetupPage } from './OrganizationSetupPage'
import { MarketingHome } from './MarketingHome'
import { SolutionsPage } from './SolutionsPage'
import { ApiDevelopersPage } from './ApiDevelopersPage'

type Json = Record<string, unknown>

function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="field"><span>{label}</span><input {...props} /></label> }
function Button({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className="button button-primary" {...props}>{children}</button> }
function Notice({ message, error = false }: { message: string; error?: boolean }) { return message ? <div className={`notice ${error ? 'error' : 'success'}`}>{message}</div> : null }
function PageTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: ReactNode }) { return <div className="page-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{children}</div> }
function AuthFrame({ children, title, eyebrow = 'IDENTITY OPERATIONS PLATFORM' }: { children: ReactNode; title: ReactNode; eyebrow?: string }) { return <div className="auth-page"><div className="auth-panel"><Link className="brand" to="/"><span className="brand-mark">T</span><span>Truvo<span className="accent">ID</span></span></Link><div className="auth-copy"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>One trusted layer for every identity decision.</p></div>{children}</div><div className="auth-visual"><div className="grid-glow" /><div className="visual-copy"><span className="eyebrow">TRUST LAYER / 001</span><strong>Every signal.<br />One clear answer.</strong></div></div></div> }

function Home() { return <MarketingHome /> }

function Login({ onLogin }: { onLogin: (profile: AuthProfile) => void }) { const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); try { tokenStore.save(await api.login(email, password)); onLogin(await api.profile()); navigate('/dashboard') } catch (error) { setMessage(error instanceof Error ? error.message : 'Sign in failed.') } } return <AuthFrame title={<>Verify with<br /><span className="gradient-text">confidence.</span></>}><form onSubmit={submit}><Field label="Email address" required type="email" value={email} onChange={event => setEmail(event.target.value)} /><Field label="Password" required type="password" value={password} onChange={event => setPassword(event.target.value)} /><Notice message={message} error /><Button>Sign in ↗</Button></form><div className="auth-foot"><Link to="/register">Create an institution account</Link><span> · </span><Link to="/accept-agency-invite">Accept agency invitation</Link></div></AuthFrame> }

function Register({ onLogin }: { onLogin: (profile: AuthProfile) => void }) { const navigate = useNavigate(); const [message, setMessage] = useState(''); const [form, setForm] = useState({ institutionName: '', adminFullName: '', adminEmail: '', password: '' }); async function submit(event: FormEvent) { event.preventDefault(); try { tokenStore.save(await api.post('/v1/auth/register', { ...form, type: 'institution' }) as never); onLogin(await api.profile()); navigate('/setup') } catch (error) { setMessage(error instanceof Error ? error.message : 'Registration failed.') } } return <AuthFrame eyebrow="CREATE AN INSTITUTION WORKSPACE" title={<>Start with<br /><span className="gradient-text">clarity.</span></>}><p className="lede">Create the workspace first. Complete your organization profile progressively.</p><form onSubmit={submit}><Field label="Institution name" required value={form.institutionName} onChange={event => setForm({ ...form, institutionName: event.target.value })} /><Field label="Administrator name" required value={form.adminFullName} onChange={event => setForm({ ...form, adminFullName: event.target.value })} /><Field label="Administrator email" required type="email" value={form.adminEmail} onChange={event => setForm({ ...form, adminEmail: event.target.value })} /><Field label="Password" required type="password" minLength={8} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /><Notice message={message} error /><Button>Create institution workspace ↗</Button></form></AuthFrame> }

function AcceptAgencyInvite() { const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const token = params.get('token') ?? ''; async function submit(event: FormEvent) { event.preventDefault(); try { await api.post('/v1/auth/agency-invitations/accept', { token, password }); setMessage('Invitation accepted. Sign in to continue.'); setTimeout(() => navigate('/login'), 900) } catch (error) { setMessage(error instanceof Error ? error.message : 'Invitation could not be accepted.') } } return <AuthFrame eyebrow="AGENCY INVITATION" title={<>Join your<br /><span className="gradient-text">agency workspace.</span></>}><p className="lede">Set your password to activate the agency administrator account.</p><form onSubmit={submit}><Field label="Password" required type="password" minLength={8} value={password} onChange={event => setPassword(event.target.value)} /><Notice message={message} error={message.includes('could')} /><Button disabled={!token}>Accept invitation ↗</Button></form></AuthFrame> }

function Shell({ profile, onLogout }: { profile: AuthProfile; onLogout: () => void }) { const location = useLocation(); const isAdmin = profile.role.toLowerCase().includes('platform'); const items = [['/dashboard', 'Overview'], ['/setup', 'Organization setup'], ['/outlets', 'Outlets'], ['/api-keys', 'API keys'], ['/wallet', 'Wallet']]; return <div className="app-shell"><aside className="sidebar"><Link className="brand" to="/dashboard"><span className="brand-mark">T</span><span>Truvo<span className="accent">ID</span></span></Link><div className="workspace-label">WORKSPACE</div><div className="workspace"><span className="workspace-dot" />{profile.institutionName || 'Platform operations'}</div><nav>{items.map(([path, label], index) => <Link className={location.pathname === path ? 'nav-link active' : 'nav-link'} key={path} to={path}><span className="nav-index">{String(index + 1).padStart(2, '0')}</span>{label}</Link>)}</nav>{isAdmin && <><div className="workspace-label admin-label">ADMIN</div><nav><Link className={location.pathname === '/admin/agencies' ? 'nav-link admin-active' : 'nav-link'} to="/admin/agencies"><span className="nav-index">A</span>Invite agencies</Link></nav></>}<div className="sidebar-footer"><div className="status"><span /> API operational</div><button className="sign-out" onClick={onLogout}>Sign out</button></div></aside><main className="main-content"><header className="topbar"><div className="mobile-brand">Truvo<span className="accent">ID</span></div><div className="topbar-actions"><span className="eyebrow">{profile.fullName || profile.email}</span><div className="avatar">{(profile.fullName || profile.email)[0].toUpperCase()}</div></div></header><div className="page-content"><Routes><Route path="/dashboard" element={<Dashboard profile={profile} />} /><Route path="/setup" element={<OrganizationSetupPage />} /><Route path="/outlets" element={<Outlets />} /><Route path="/api-keys" element={<ApiKeysPage />} /><Route path="/wallet" element={<Wallet />} />{isAdmin && <Route path="/admin/agencies" element={<InviteAgency />} />}<Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></div></main></div> }

function Dashboard({ profile }: { profile: AuthProfile }) { return <section><PageTitle eyebrow="TENANT WORKSPACE" title="Welcome to TruvoID."><p className="lede">Your workspace is ready. Complete the organization profile progressively, then configure operations when you are ready.</p></PageTitle><div className="activity-card"><div><div className="eyebrow">ORGANIZATION SETUP</div><h2>Build a complete organization profile.</h2><p>Save information section by section. Outlets, API keys, and wallet funding remain optional until operations begin.</p></div><Link className="button button-primary" to="/setup">Open setup center ↗</Link></div>{profile.role.toLowerCase().includes('agency') && <div className="activity-card"><div><div className="eyebrow">AGENCY OPERATIONS</div><h2>Build your outlet network.</h2><p>Create outlets and issue credentials after your agency profile is ready.</p></div><Link className="button button-primary" to="/outlets">Manage outlets ↗</Link></div>}</section> }

function Outlets() { const [items, setItems] = useState<Json[]>([]); const [name, setName] = useState(''); const [message, setMessage] = useState(''); async function load() { try { setItems(await api.get<Json[]>('/v1/tenant/outlets')) } catch { setItems([]) } } useEffect(() => { void load() }, []); async function create(event: FormEvent) { event.preventDefault(); try { await api.post('/v1/tenant/outlets', { name }); setName(''); setMessage('Outlet created.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create outlet.') } } return <section><PageTitle eyebrow="AGENCY / OUTLETS" title="Your outlets."><p className="lede">Create outlets after your organization profile is ready.</p></PageTitle><div className="form-card inline-form"><form onSubmit={create}><Field label="Outlet name" required value={name} onChange={event => setName(event.target.value)} placeholder="Lagos branch" /><Button>Create outlet ↗</Button></form><Notice message={message} error={message.startsWith('Could')} /></div>{items.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Wallet</th></tr></thead><tbody>{items.map(item => <tr key={String(item.id)}><td>{String(item.name)}</td><td>{String(item.status)}</td><td>{String(item.walletId)}</td></tr>)}</tbody></table></div> : <div className="empty">No outlets yet.</div>}</section> }

function Wallet() { const [balance, setBalance] = useState<Json>({}); useEffect(() => { api.get<Json>('/v1/tenant/wallet/balance').then(setBalance).catch(() => undefined) }, []); return <section><PageTitle eyebrow="TENANT / WALLET" title="Wallet."><p className="lede">Funding is optional during onboarding and available here when operations are ready.</p></PageTitle><div className="wallet-hero"><div><span className="stat-label">AVAILABLE BALANCE</span><strong>₦{(Number(balance.balanceKobo ?? 0) / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}</strong><span className="stat-note">Tenant wallet balance</span></div></div></section> }

function InviteAgency() { const [form, setForm] = useState({ agencyName: '', adminFullName: '', adminEmail: '' }); const [invite, setInvite] = useState(''); const [message, setMessage] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); try { const result = await api.post<Json>('/v1/admin/agencies/invite', form); setInvite(`${window.location.origin}/accept-agency-invite?token=${String(result.invitationToken)}`); setMessage('Invitation created. Copy the link and send it to the agency administrator.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create invitation.') } } return <section><PageTitle eyebrow="PLATFORM / AGENCIES" title="Invite an agency."><p className="lede">Agencies enter the platform through an administrator invitation.</p></PageTitle><div className="form-card narrow"><form onSubmit={submit}><Field label="Agency name" required value={form.agencyName} onChange={event => setForm({ ...form, agencyName: event.target.value })} /><Field label="Administrator name" required value={form.adminFullName} onChange={event => setForm({ ...form, adminFullName: event.target.value })} /><Field label="Administrator email" required type="email" value={form.adminEmail} onChange={event => setForm({ ...form, adminEmail: event.target.value })} /><Button>Generate invitation ↗</Button></form><Notice message={message} error={message.startsWith('Could')} />{invite && <div className="key-reveal"><span>Invitation link</span><code>{invite}</code></div>}</div></section> }

export function App() { const [profile, setProfile] = useState<AuthProfile | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { if (!tokenStore.accessToken) { setLoading(false); return } api.profile().then(setProfile).catch(() => tokenStore.clear()).finally(() => setLoading(false)) }, []); if (loading) return <div className="loading-screen"><span className="brand-mark">T</span><span className="pulse" /></div>; if (profile) return <Shell profile={profile} onLogout={() => { tokenStore.clear(); setProfile(null) }} />; return <Routes><Route path="/" element={<Home />} /><Route path="/solutions" element={<SolutionsPage />} /><Route path="/api-and-developers" element={<ApiDevelopersPage />} /><Route path="/login" element={<Login onLogin={setProfile} />} /><Route path="/register" element={<Register onLogin={setProfile} />} /><Route path="/accept-agency-invite" element={<AcceptAgencyInvite />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
