import { Link } from 'react-router-dom'

const services = [
  ['NIN', 'National identity', 'Verify demographic identity records in real time.', '11-digit NIN'],
  ['BVN', 'Bank verification', 'Confirm identity-to-account relationships for financial workflows.', '11-digit BVN'],
  ['CAC', 'Business verification', 'Inspect registration status, filings, and directorship.', 'RC / BN number'],
  ['TIN', 'Tax identification', 'Support tax and corporate compliance checks.', 'FIRS / JTB TIN'],
]

export function MarketingHome() {
  return <div className="marketing-site">
    <MarketingNav />
    <main>
      <section className="marketing-hero">
        <div className="hero-grid" />
        <div className="marketing-container hero-layout">
          <div className="hero-copy">
            <span className="marketing-kicker"><i /> KYC / KYB / IDENTITY OPERATIONS</span>
            <h1>Identity verification, <em>built for business.</em></h1>
            <p>Verify people and businesses, manage identity operations, and connect trusted verification directly to your systems.</p>
            <div className="hero-actions"><Link className="marketing-button primary" to="/register">Create a workspace <span>↗</span></Link><a className="marketing-button ghost" href="#solutions">Explore the platform</a></div>
            <div className="proof-row"><span><b>●</b> NDPA-aligned controls</span><span><b>●</b> Outlet-ready architecture</span><span><b>●</b> API-first</span></div>
          </div>
          <OperationalTerminal />
        </div>
      </section>
      <section className="signal-strip"><div className="marketing-container signal-items"><span>ONE TRUST LAYER</span><strong>For every identity decision</strong><span>REAL-TIME VERIFICATION</span><span>CONTROLLED ACCESS</span><span>AUDITABLE OPERATIONS</span></div></section>
      <section className="marketing-section muted" id="solutions"><div className="marketing-container"><SectionHeading kicker="TRUSTED IDENTITY OPERATIONS" title="Know who you are dealing with." copy="TruvoID gives organizations the tools to verify identities and manage the full operational journey from one secure workspace." /><div className="proof-grid">{[['01', '99.9%', 'Built for uptime', 'Keep customer and compliance workflows moving through peak verification cycles.'], ['02', '<400ms', 'Direct inquiries', 'Fast, predictable responses for the moments where drop-off costs revenue.'], ['03', '1 → ∞', 'Organization to outlet', 'Start centralized, then scale into isolated outlets without changing your operating model.']].map(([number, stat, title, copy]) => <article className="proof-card" key={number}><span className="card-index">{number}</span><strong>{stat}</strong><h3>{title}</h3><p>{copy}</p><span className="card-line" /></article>)}</div></div></section>
      <section className="marketing-section" id="verification"><div className="marketing-container"><SectionHeading kicker="COVERAGE SPECTRUM" title="Verify the identities that matter." copy="A focused verification layer for onboarding, compliance, fraud prevention, and everyday trust decisions." /><div className="service-grid">{services.map(([code, title, copy, input]) => <article className="service-card" key={code}><div className="service-top"><span>{code}</span><i>↗</i></div><h3>{title}</h3><p>{copy}</p><div className="service-meta"><span>INPUT / {input}</span><b>ACTIVE API</b></div></article>)}<article className="service-card featured"><span className="marketing-kicker">ORCHESTRATION</span><h3>Chain the signals.</h3><p>Combine KYC and KYB checks into a single approval journey with clear ownership and auditable outcomes.</p><a href="#developers">Talk to solutions <span>→</span></a></article></div></div></section>
      <section className="marketing-section architecture muted"><div className="marketing-container"><SectionHeading kicker="ARCHITECTURE MODEL" title="One platform. Different ways to operate." copy="Whether you run one organization or a distributed network, TruvoID gives your teams the right level of control." /><div className="model-grid"><ModelCard type="INSTITUTIONS" title="One workspace, fully governed." copy="Create a central organization workspace, invite your team, complete verification setup, and connect your systems when ready." items={['Progressive organization onboarding', 'Role-aware team access', 'Central wallet and activity', 'Scoped API credentials']} /><ModelCard type="AGENCIES" title="A network of trusted outlets." copy="Manage branches, clients, or franchise locations from one agency workspace while keeping wallets, credentials, and activity isolated." items={['Invited agency access', 'Independent outlet wallets', 'API key per outlet', 'Central oversight']} gold /></div></div></section>
      <section className="marketing-section developer" id="developers"><div className="marketing-container developer-layout"><div><SectionHeading kicker="DEVELOPER INFRASTRUCTURE" title="Your systems. Our verification layer." copy="Generate scoped credentials, send verification requests, and monitor operational usage without exposing user credentials." /><div className="developer-steps"><div><b>01</b><span><strong>Generate scoped access</strong>Give every outlet or service its own credential.</span></div><div><b>02</b><span><strong>Send a trusted request</strong>Use consistent verification payloads from your stack.</span></div><div><b>03</b><span><strong>Operate with visibility</strong>Review activity, wallet usage, and audit signals.</span></div></div><Link className="marketing-button primary" to="/api-docs.html">Read API documentation <span>↗</span></Link></div><CodeTerminal /></div></section>
      <section className="marketing-section security" id="security"><div className="marketing-container security-grid"><div><SectionHeading kicker="GOVERNANCE & RESILIENCE" title="Identity data deserves serious infrastructure." copy="Control how access is granted, how activity is recorded, and how organizations scale without losing visibility." /></div><div className="security-list">{['Controlled API access', 'Key rotation and revocation', 'Organization-level isolation', 'Outlet-level activity trails', 'Wallet safeguards', 'Progressive compliance setup'].map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><i>↗</i></div>)}</div></div></section>
      <section className="marketing-cta"><div className="marketing-container"><span className="marketing-kicker">START WITH THE TRUST LAYER</span><h2>Build confidence into every interaction.</h2><p>Start with a workspace. Add your organization detail progressively. Connect verification when your team is ready.</p><div className="hero-actions"><Link className="marketing-button gold" to="/register">Create a workspace <span>↗</span></Link><a className="marketing-button dark-ghost" href="mailto:hello@truvoid.com">Talk to sales</a></div></div></section>
    </main>
    <footer className="marketing-footer"><div className="marketing-container footer-grid"><div><Link className="marketing-logo" to="/"><span>T</span>TruvoID</Link><p>Verify. Know. Operate.</p></div><div><b>PLATFORM</b><a href="#verification">Verification</a><a href="#solutions">Solutions</a><a href="#developers">API & developers</a></div><div><b>COMPANY</b><a href="mailto:hello@truvoid.com">Contact</a><a href="#security">Security</a><a href="/api-docs.html">Documentation</a></div><div><b>ACCESS</b><Link to="/login">Log in</Link><Link to="/register">Get started</Link></div></div><div className="marketing-container footer-bottom"><span>© 2026 TruvoID</span><span>Identity operations for modern organizations.</span></div></footer>
  </div>
}

export function MarketingNav() { return <header className="marketing-nav"><div className="marketing-container nav-inner"><Link className="marketing-logo" to="/"><span>T</span>TruvoID</Link><nav><Link to="/solutions">Solutions</Link><a href="/#verification">Verification</a><Link to="/api-and-developers">API & developers</Link><a href="/#security">Security</a></nav><div className="nav-actions"><Link to="/login">Log in</Link><Link className="nav-cta" to="/register">Get started <span>↗</span></Link></div></div></header> }
function SectionHeading({ kicker, title, copy }: { kicker: string; title: string; copy: string }) { return <div className="section-heading-marketing"><span className="marketing-kicker"><i /> {kicker}</span><h2>{title}</h2><p>{copy}</p></div> }
function ModelCard({ type, title, copy, items, gold = false }: { type: string; title: string; copy: string; items: string[]; gold?: boolean }) { return <article className={gold ? 'model-card gold-edge' : 'model-card'}><span className="model-type">{type}</span><h3>{title}</h3><p>{copy}</p><ul>{items.map(item => <li key={item}><b>✓</b>{item}</li>)}</ul><a href={gold ? '#developers' : '#solutions'}>Explore {type.toLowerCase()} <span>→</span></a></article> }
function OperationalTerminal() { return <div className="op-terminal"><div className="terminal-glow" /><div className="terminal-head"><div><span className="terminal-dot live" /> LIVE TRANSACTION HUB</div><span>SYS / ACTIVE</span></div><div className="terminal-balance"><small>PRIMARY BALANCE</small><strong>₦ 4,892,500.00</strong></div><div className="terminal-event"><div><b>NIN</b><span><strong>6839 •••• •••• 9214</strong><small>Identity match / Adebayo C.</small></span></div><em>VERIFIED<br /><small>0.38s</small></em></div><div className="terminal-event"><div><b className="blue">CAC</b><span><strong>RC-1849204 / APEX DYNAMICS</strong><small>Active status / directorship</small></span></div><em>MATCH<br /><small>0.44s</small></em></div><div className="terminal-metrics"><span><small>REQUESTS</small><b>142,881</b></span><span><small>ACCURACY</small><b>99.98%</b></span><span><small>LATENCY</small><b>390ms</b></span></div><div className="terminal-response"><span>POST /v1/tenant/verification-calls/reserve <b>200 OK</b></span><code>{`{ "status": "success", "verified": true, "confidence": 0.998 }`}</code></div></div> }
function CodeTerminal() { return <div className="code-terminal"><div className="code-head"><span><i /> <i /> <i /> <b>truvo / verification</b></span><em>LIVE API</em></div><pre><code><span className="comment">// reserve a verification call</span>{'\n'}<span className="purple">curl</span> -X POST https://api.truvoid.com/v1/tenant/verification-calls/reserve \{`\n`}  -H <span className="gold">"X-API-Key: trv_live_••••"</span> \{`\n`}  -H <span className="gold">"Content-Type: application/json"</span> \{`\n`}  -d <span className="green">'{`{ "verificationType": "nin", "subjectRef": "hashed-ref" }`}'</span>{'\n\n'}<span className="comment">// 200 OK / 312ms</span>{'\n'}{`{`}<span className="key">"status"</span>: <span className="green">"reserved"</span>,{`\n`}  <span className="key">"reference"</span>: <span className="green">"TRV_REF_83901928"</span>{`\n}`}</code></pre><div className="code-foot">SDKs and examples <span>Node / Python / PHP / Go</span></div></div> }
