import { FormEvent, useEffect, useState } from 'react'
import { api } from './api'

type Json = Record<string, unknown>
type Setup = { sections: Record<string, Json>; accessLevel?: number; attested: boolean; status: string; progress: number; documents: { documentType: string; fileName: string; status: string }[]; editable?: boolean; reviewNote?: string | null; submittedAt?: string | null; reviewedAt?: string | null }

/** Tells the app shell to re-read /me (setup status drives the test-mode banner and the Live switch). */
export const PROFILE_CHANGED_EVENT = 'truvoid:profile-changed'

function ReviewStatus({ setup }: { setup: Setup }) {
  if (setup.status === 'submitted') return <div className="review-status pending"><strong>Under review</strong><span>Submitted {setup.submittedAt ? new Date(setup.submittedAt).toLocaleDateString() : ''}. TruvoID is reviewing your profile; editing is paused until then. Test mode stays available.</span></div>
  if (setup.status === 'needs_changes') return <div className="review-status failed"><strong>Changes requested</strong><span>{setup.reviewNote ?? 'TruvoID asked for changes.'} Update the profile and submit it again.</span></div>
  if (setup.status === 'approved') return <div className="review-status match"><strong>Approved</strong><span>Live verification is enabled. Contact TruvoID support to change approved details.</span></div>
  return <div className="review-status"><strong>Test mode</strong><span>You can use free test verifications now. Complete and submit this profile to go live once TruvoID approves it.</span></div>
}

const sections = [
  ['general', 'Organization details', 'Registered company information, addresses, TIN, and industry.'],
  ['contacts', 'Primary contact', 'The people TruvoID should contact about this organization.'],
  ['business', 'Business information', 'What the organization does and who it serves.'],
  ['ownership', 'Ownership', 'Shareholders who own more than five percent.'],
  ['directors', 'Directors', 'Organization directors and appointment dates.'],
  ['services', 'Verification services', 'The KYC and KYB services the organization needs.'],
  ['integration', 'API and integration', 'Technical requirements, when the organization is ready to integrate.'],
  ['compliance', 'Compliance', 'Regulatory, AML/KYC, and data-protection information.'],
  ['legal', 'Legal history', 'Recent disputes, claims, or other legal information.'],
]

export function OrganizationSetupPage() {
  const [setup, setSetup] = useState<Setup | null>(null); const [active, setActive] = useState('general'); const [draft, setDraft] = useState<Json>({}); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function load() { const result = await api.get<Setup>('/v1/tenant/setup'); setSetup(result); setDraft(result.sections[active] ?? {}); return result }
  useEffect(() => { void load().catch(() => setError('Organization setup could not be loaded.')) }, [])
  // Switching sections first persists the current one, so an administrator who fills
  // several sections without pressing "Save section" doesn't silently lose edits.
  async function select(section: string) {
    if (busy) return
    const tabs = ['access', 'documents', 'review']
    const unsaved = setup && setup.editable !== false && active !== section && !tabs.includes(active)
      && JSON.stringify(draft) !== JSON.stringify(setup.sections[active] ?? {})
    if (unsaved) {
      setBusy(true)
      try {
        await api.put(`/v1/tenant/setup/${active}`, draft)
        const refreshed = await load()
        setBusy(false)
        setActive(section); setDraft(refreshed.sections[section] ?? {}); setMessage(''); setError('')
      } catch (reason) {
        setError(reason instanceof Error ? reason.message : 'Could not save the current section.')
        setBusy(false)
      }
      return
    }
    setActive(section); setDraft(setup?.sections[section] ?? {}); setMessage(''); setError('')
  }
  async function save(event?: FormEvent) { event?.preventDefault(); if (busy) return; setBusy(true); try { await api.put(`/v1/tenant/setup/${active}`, draft); setMessage('Section saved.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save section.') } finally { setBusy(false) } }
  async function saveAccess(level: number) { if (busy) return; setBusy(true); try { await api.put('/v1/tenant/setup/access-level', { level }); setMessage('Access level saved.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save access level.') } finally { setBusy(false) } }
  async function attest() { if (busy) return; setBusy(true); try { await api.put('/v1/tenant/setup/attestation', { accepted: true }); setMessage('Attestation saved.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save attestation.') } finally { setBusy(false) } }
  async function submit() { if (busy) return; setBusy(true); try { await api.post('/v1/tenant/setup/submit', {}); setMessage('Organization profile submitted for review.'); await load(); window.dispatchEvent(new Event(PROFILE_CHANGED_EVENT)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Complete the required sections first.') } finally { setBusy(false) } }
  async function upload(event: React.ChangeEvent<HTMLInputElement>, documentType: string) { const file = event.target.files?.[0]; if (!file || busy) return; const data = new FormData(); data.append('file', file); data.append('documentType', documentType); setBusy(true); try { await api.upload('/v1/tenant/setup/documents', data); setMessage('Document uploaded.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not upload document.') } finally { setBusy(false) } }
  if (!setup) return <section><div className="empty">Loading organization setup...</div></section>
  const current = sections.find(section => section[0] === active) ?? sections[0]
  const locked = setup.editable === false
  return <section><div className="page-title"><div className="eyebrow">ORGANIZATION SETUP</div><h1>Complete your profile.</h1><p className="lede">Save each section as you go. You can leave optional integration details for later.</p></div><ReviewStatus setup={setup} /><div className="setup-progress"><div><span className="stat-label">PROFILE COMPLETION</span><strong>{setup.progress}%</strong></div><div className="progress-track"><span style={{ width: `${setup.progress}%` }} /></div></div><div className="setup-layout"><aside className="setup-nav">{sections.map(section => <button disabled={busy} className={active === section[0] ? 'step active' : 'step'} key={section[0]} onClick={() => void select(section[0])}>{section[1]}</button>)}<button disabled={busy} className={active === 'access' ? 'step active' : 'step'} onClick={() => void select('access')}>Access level</button><button disabled={busy} className={active === 'documents' ? 'step active' : 'step'} onClick={() => void select('documents')}>Documents</button><button disabled={busy} className={active === 'review' ? 'step active' : 'step'} onClick={() => void select('review')}>Review & submit</button></aside><main className="form-card setup-card">{active === 'access' ? <AccessLevel value={setup.accessLevel} onSave={saveAccess} busy={busy || locked} /> : active === 'documents' ? <Documents documents={setup.documents} onUpload={upload} busy={busy || locked} /> : active === 'review' ? <Review setup={setup} onAttest={attest} onSubmit={submit} busy={busy || locked} /> : <><div className="eyebrow">{current[0].toUpperCase()} / PROFILE</div><h2>{current[1]}</h2><p className="lede">{current[2]}</p><form onSubmit={save}><fieldset className="setup-fieldset" disabled={locked}><SectionFields section={active} values={draft} onChange={setDraft} /></fieldset><div className="setup-actions"><button disabled={busy || locked} className="button button-primary">{busy ? 'Saving...' : 'Save section ↗'}</button>{message && <span className="stat-note">{message}</span>}{error && <span className="notice error">{error}</span>}</div></form></>}</main></div></section>
}

function SectionFields({ section, values, onChange }: { section: string; values: Json; onChange: (values: Json) => void }) {
  const set = (key: string, value: unknown) => onChange({ ...values, [key]: value })
  const input = (key: string, label: string, type = 'text') => <label className="field" key={key}><span>{label}</span><input type={type} value={String(values[key] ?? '')} onChange={event => set(key, event.target.value)} /></label>
  if (section === 'general') return <>{input('registeredCompanyName', 'Registered company name')}{input('country', 'Country of operation')}{input('tradingName', 'Trading name')}{input('incorporationNumber', 'Incorporation number')}{input('registeredOfficeAddress', 'Registered office address')}{input('operationalOfficeAddress', 'Operational office address')}{input('tin', 'TIN')}{input('industry', 'Industry of operation')}</>
  if (section === 'contacts') return <><h3>Primary contact</h3>{input('primaryFirstName', 'First name')}{input('primaryLastName', 'Last name')}{input('primaryPosition', 'Position')}{input('primaryEmail', 'Email', 'email')}{input('primaryPhone', 'Phone')}{input('primaryNin', 'NIN')}<h3>Secondary contact (optional)</h3>{input('secondaryName', 'Full name')}{input('secondaryEmail', 'Email', 'email')}{input('secondaryPhone', 'Phone')}{input('secondaryNin', 'NIN')}</>
  if (section === 'business') return <>{input('natureOfBusiness', 'Nature of business')}{input('targetMarkets', 'Primary target markets')}</>
  if (section === 'ownership') return <><p className="stat-note">Add shareholders who own more than 5%. Use one shareholder per line: Full name - ownership percentage.</p><label className="field"><span>Shareholders</span><textarea rows={8} value={String(values.shareholders ?? '')} onChange={event => set('shareholders', event.target.value)} /></label></>
  if (section === 'directors') return <><p className="stat-note">Use one director per line: Full name - appointment date.</p><label className="field"><span>Directors</span><textarea rows={8} value={String(values.directors ?? '')} onChange={event => set('directors', event.target.value)} /></label></>
  if (section === 'services') return <><label className="check"><input type="checkbox" checked={Boolean(values.nin)} onChange={event => set('nin', event.target.checked)} /> NIN</label><label className="check"><input type="checkbox" checked={Boolean(values.bvn)} onChange={event => set('bvn', event.target.checked)} /> BVN</label><label className="check"><input type="checkbox" checked={Boolean(values.driversLicense)} onChange={event => set('driversLicense', event.target.checked)} /> Driver's license</label><label className="check"><input type="checkbox" checked={Boolean(values.businessVerification)} onChange={event => set('businessVerification', event.target.checked)} /> Business verification (CAC)</label><label className="check"><input type="checkbox" checked={Boolean(values.tin)} onChange={event => set('tin', event.target.checked)} /> TIN</label></>
  if (section === 'integration') return <><label className="check"><input type="checkbox" checked={Boolean(values.integrating)} onChange={event => set('integrating', event.target.checked)} /> We are integrating TruvoID now</label>{Boolean(values.integrating) && <>{input('technicalContactName', 'Technical contact name')}{input('technicalContactEmail', 'Technical contact email', 'email')}{input('environment', 'Environment')}{input('privacyRequirements', 'Data privacy requirements')}{input('integrationGoals', 'Integration goals')}{input('volume', 'Expected API volume')}{input('processing', 'Processing model')}{input('responseFormat', 'Response format')}{input('desiredStartDate', 'Desired start date', 'date')}{input('expectedCompletionDate', 'Expected completion date', 'date')}</>}</>
  if (section === 'compliance') return <>{input('regulatoryRegistration', 'Regulatory registration details')}{input('complianceRequirements', 'Compliance or reporting requirements')}{input('amlKycProgram', 'AML/KYC program')}{input('dataProtection', 'Data protection compliance')}</>
  return <><label className="check"><input type="checkbox" checked={Boolean(values.hasLegalHistory)} onChange={event => set('hasLegalHistory', event.target.checked)} /> Legal disputes or claims in the last five years</label>{Boolean(values.hasLegalHistory) && <label className="field"><span>Details</span><textarea rows={8} value={String(values.details ?? '')} onChange={event => set('details', event.target.value)} /></label>}</>
}

function AccessLevel({ value, onSave, busy }: { value?: number; onSave: (level: number) => void; busy: boolean }) { return <><div className="eyebrow">SERVICE ACCESS</div><h2>Choose your verification access level.</h2><p className="lede">Start with what your organization needs. This can be reviewed later.</p><div className="access-levels">{[1, 2, 3, 4, 5].map(level => <button disabled={busy} className={value === level ? 'access-level selected' : 'access-level'} key={level} onClick={() => onSave(level)}><strong>{busy && value !== level ? 'Saving...' : `Level ${level}`}</strong><span>{['Photography and names', 'Level 1 plus address, signature, and telephone', 'Level 2 plus maiden name and birth details', 'Level 3 plus origin, next of kin, and history', 'Level 4 plus biometric and security information'][level - 1]}</span></button>)}</div></> }
function Documents({ documents, onUpload, busy }: { documents: { documentType: string; fileName: string; status: string }[]; onUpload: (event: React.ChangeEvent<HTMLInputElement>, documentType: string) => void; busy: boolean }) { const [type, setType] = useState('certificate_of_incorporation'); return <><div className="eyebrow">SUPPORTING DOCUMENTS</div><h2>Upload organization documents.</h2><p className="lede">Upload the documents required to verify your organization. Maximum file size is 10 MB.</p><label className="field"><span>Document type</span><select disabled={busy} value={type} onChange={event => setType(event.target.value)}><option value="certificate_of_incorporation">Certificate of incorporation</option><option value="memart">MEMART / Articles of association</option><option value="status_report">Updated status report</option><option value="director_id">Director ID document</option><option value="proof_of_address">Proof of address</option><option value="nin_supporting">NIN supporting document</option><option value="data_processing_policy">Data processing policy</option><option value="ndpa_certificate">NDPA certificate</option><option value="other">Other supporting document</option></select></label><label className={`button button-primary upload-button ${busy ? 'disabled' : ''}`}>{busy ? 'Uploading...' : 'Upload document'}<input disabled={busy} type="file" hidden onChange={event => onUpload(event, type)} /></label>{documents.length ? <div className="document-list">{documents.map((document, index) => <div className="document-row" key={`${document.fileName}-${index}`}><strong>{document.fileName}</strong><span>{document.documentType} / {document.status}</span></div>)}</div> : <div className="empty">No supporting documents uploaded.</div>}</> }
function Review({ setup, onAttest, onSubmit, busy }: { setup: Setup; onAttest: () => void; onSubmit: () => void; busy: boolean }) { return <><div className="eyebrow">FINAL STEP</div><h2>Review and submit.</h2><p className="lede">Confirm your information before sending the organization profile for review.</p><div className="review-list">{sections.map(section => <div key={section[0]}><span>{section[1]}</span><strong>{Object.keys(setup.sections[section[0]] ?? {}).length ? 'Complete' : 'Needs information'}</strong></div>)}<div><span>Documents</span><strong>{setup.documents.length ? 'Complete' : 'Needs information'}</strong></div><div><span>Access level</span><strong>{setup.accessLevel ? `Level ${setup.accessLevel}` : 'Needs information'}</strong></div></div><label className="check"><input disabled={busy} type="checkbox" checked={setup.attested} onChange={onAttest} /> I confirm that the information provided is true, accurate, and complete.</label><button disabled={busy} className="button button-primary" onClick={onSubmit}>{busy ? 'Submitting...' : 'Submit organization profile ↗'}</button></> }
