import { Link } from 'react-router-dom'
import { MarketingNav } from './MarketingHome'

const accessLevels = [
  ['01', 'Basic match', 'Confirm identity validity with the minimum information needed for a decision.', 'Low-risk onboarding'],
  ['02', 'Enhanced verification', 'Use richer demographic signals for standard compliance workflows.', 'Fintech and lending'],
  ['03', 'Complete assurance', 'Support high-assurance workflows with expanded evidence and review paths.', 'Regulated operations'],
]

export function SolutionsPage() {
  return <div className="marketing-site solutions-site"><MarketingNav /><main>
    <div className="solutions-ribbon"><div className="marketing-container"><span><i /> SOLUTIONS / ARCHITECTURE</span><strong>Progressive access. Structured operations.</strong></div></div>
    <section className="solutions-hero"><div className="marketing-container solutions-hero-grid"><div><span className="marketing-kicker"><i /> BUILT FOR MODERN ORGANIZATIONS</span><h1>Verification infrastructure that fits how you operate.</h1><p>Start with one organization workspace or build a controlled network of outlets. TruvoID gives your teams the verification services, access controls, and operational visibility to grow with confidence.</p><div className="hero-actions"><Link className="marketing-button primary" to="/register">Create an institution workspace <span>↗</span></Link><a className="marketing-button ghost" href="#institutions">Explore architecture</a></div></div><div className="solutions-status"><div className="status-head"><span>PLATFORM STATUS</span><b><i /> OPERATIONAL</b></div><div className="status-row"><span>Tenant workspaces</span><strong>ISOLATED</strong></div><div className="status-row"><span>Outlet credentials</span><strong>SCOPED</strong></div><div className="status-row"><span>Verification activity</span><strong>AUDITABLE</strong></div><div className="status-code">ORG_SETUP / ACCESS_POLICY / READY</div></div></div></section>
    <section className="marketing-section muted" id="institutions"><div className="marketing-container solution-split"><div><span className="marketing-kicker"><i /> ENTERPRISE SCOPE</span><h2>Institutions</h2><h3>Run identity verification from one workspace.</h3><p>Institutions can create an account quickly, complete their organization profile progressively, and configure operations when ready. No forced outlet creation, API setup, or wallet funding during signup.</p><ul className="solution-checks">{['Progressive organization setup', 'Team and role management', 'KYC and KYB verification', 'Wallet and usage visibility', 'Scoped API credentials', 'Activity and audit review'].map(item => <li key={item}><b>✓</b>{item}</li>)}</ul><Link className="text-link" to="/register">Start as an institution →</Link></div><InstitutionConsole /></div></section>
    <section className="marketing-section" id="agencies"><div className="marketing-container"><div className="section-heading-marketing"><span className="marketing-kicker"><i /> HIERARCHICAL OPERATIONS</span><h2>Agencies</h2><p>One agency. Multiple outlets. One platform. Agencies enter by invitation, then create the operating network as their business grows.</p></div><div className="outlet-capabilities">{[['01', 'Its own workspace view', 'Give each outlet a clear operating boundary.'], ['02', 'Its own API key', 'Issue credentials tied to the outlet that uses them.'], ['03', 'Its own wallet', 'Keep outlet funding and verification usage visible.'], ['04', 'Its own activity', 'Review localized verification and audit signals.'], ['05', 'Its own status', 'Suspend or control an outlet without losing parent visibility.']].map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="outlet-tree"><div><span className="marketing-kicker"><i /> AGENCY ARCHITECTURE</span><h3>Central oversight. Federated operations.</h3></div><div className="tree-nodes"><div className="tree-node root"><b>Agency workspace</b><span>Central control and visibility</span></div><div className="tree-node"><b>Outlet / Lagos</b><span>Scoped key · outlet wallet</span></div><div className="tree-node"><b>Outlet / Abuja</b><span>Scoped key · outlet wallet</span></div><div className="tree-node"><b>Outlet / Port Harcourt</b><span>Scoped key · outlet wallet</span></div></div></div></div></section>
    <section className="marketing-section muted"><div className="marketing-container"><div className="section-heading-marketing centered"><span className="marketing-kicker"><i /> INSTITUTIONAL RAILS</span><h2>Verification types</h2><p>Build person and business validation into your onboarding, compliance, and fraud workflows.</p></div><div className="kyc-grid"><article className="kyc-card"><span className="kyc-label">KYC / INDIVIDUALS</span><h3>Know Your Customer</h3><p>Verify identity records and demographic signals for customer onboarding and account decisions.</p><div className="token-row"><span>NIN</span><span>BVN</span><span>Driver's license</span></div><Link to="/#verification">Explore KYC →</Link></article><article className="kyc-card gold"><span className="kyc-label">KYB / CORPORATES</span><h3>Know Your Business</h3><p>Verify organizations, directors, ownership, registration status, and business identity.</p><div className="token-row"><span>CAC</span><span>TIN</span><span>Director checks</span></div><Link to="/#verification">Explore KYB →</Link></article></div></div></section>
    <section className="marketing-section access-section" id="access-levels"><div className="marketing-container"><div className="section-heading-marketing"><span className="marketing-kicker"><i /> COMPLIANCE BY ARCHITECTURE</span><h2>Choose the access level your operation requires.</h2><p>Progressive access keeps teams focused on the data they need for a justified verification decision.</p></div><div className="access-grid">{accessLevels.map(([number, title, copy, recommendation], index) => <article className={index === 1 ? 'access-card selected' : 'access-card'} key={number}><span>{number} / ACCESS LEVEL</span><h3>{title}</h3><p>{copy}</p><div><b>RECOMMENDED FOR</b><strong>{recommendation}</strong></div></article>)}</div><div className="privacy-note"><span>⌁</span><p><b>Data minimization by default.</b> Build verification workflows around the information your organization is permitted and prepared to use.</p></div></div></section>
    <section className="marketing-cta"><div className="marketing-container"><span className="marketing-kicker">INSTITUTIONAL DEPLOYMENT</span><h2>Ready to modernize your identity operations?</h2><p>Start with a workspace, invite the right people, and configure verification when your organization is ready.</p><div className="hero-actions"><Link className="marketing-button gold" to="/register">Get started as an institution <span>↗</span></Link><a className="marketing-button dark-ghost" href="mailto:hello@truvoid.com">Talk to sales</a></div></div></section>
  </main><footer className="marketing-footer"><div className="marketing-container footer-bottom"><span>© 2026 TruvoID</span><span>Verify. Know. Operate.</span></div></footer></div>
}

function InstitutionConsole() { return <div className="institution-console"><div className="console-head"><span><i /> INSTITUTION WORKSPACE</span><b>PROFILE / 62%</b></div><div className="console-title"><div><strong>Apex Merchant Bank</strong><small>Organization workspace / active setup</small></div><span>SETUP IN PROGRESS</span></div><div className="console-stats"><div><small>CHECKS TODAY</small><b>24,819</b></div><div><small>ACTIVE KEYS</small><b>08</b></div><div><small>WALLET</small><b>₦128k</b></div></div><div className="console-feed"><span><i className="green" /> NIN / VERIFIED <b>0.38s</b></span><span><i /> CAC / MATCH <b>0.44s</b></span><span><i className="gold-dot" /> TIN / IN REVIEW <b>—</b></span></div></div> }
