import { useEffect, useState } from 'react'
import { api } from './api'

type Call = { id: string; verificationType: string; status: string; subjectPreview: string; createdAt: string; completedAt?: string }

export function VerificationHistoryPage() {
  const [items, setItems] = useState<Call[]>([]); const [status, setStatus] = useState(''); const [type, setType] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); setError(''); try { const result = await api.get<{ items: Call[] }>(`/v1/tenant/verification-calls?page=1&pageSize=50${status ? `&status=${status}` : ''}${type ? `&type=${type}` : ''}`); setItems(result.items) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Verification history could not be loaded.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [status, type])
  return <section><div className="page-title"><div className="eyebrow">VERIFICATION / HISTORY</div><h1>Verification activity.</h1><p className="lede">Review reservation requests, statuses, and references across your tenant scope.</p></div><div className="history-filters"><label className="field"><span>Type</span><select value={type} onChange={event => setType(event.target.value)}><option value="">All types</option><option value="nin">NIN</option><option value="bvn">BVN</option><option value="phone">Phone</option></select></label><label className="field"><span>Status</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option></select></label></div>{loading ? <div className="empty">Loading verification activity...</div> : error ? <div className="empty error" role="alert">{error}<br /><button className="retry-button" onClick={() => void load()}>Retry</button></div> : items.length ? <div className="table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Subject</th><th>Reference</th><th>Created</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.verificationType.toUpperCase()}</td><td><span className={`badge ${item.status}`}>{item.status}</span></td><td><code>{item.subjectPreview}...</code></td><td><code>{item.id.slice(0, 12)}</code></td><td>{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="empty">No verification calls match these filters.</div>}</section>
}
